//
// WindowsThumbnail.idl : IDL source for WindowsThumbnail
//
// This file is part of PeerProject (peerproject.org) © 2009
// Portions Copyright Nikolay Raspopov, 2009.
//
// PeerProject is free software; you can redistribute it
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 3
// of the License, or later version (at your option).
//
// PeerProject is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License 3.0
// along with PeerProject; if not, write to Free Software Foundation, Inc.
// 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA  (www.fsf.org)
//

import "oaidl.idl";
import "ocidl.idl";
import "PeerProject.idl";

[
	uuid(3772E712-75B5-4AAF-B423-FD7C0399F13F),
	version(1.0),
	helpstring("WindowsThumbnail 1.0 Type Library")
]
library WindowsThumbnailLib
{
	importlib("stdole2.tlb");

	[
		uuid(0EEA2A0F-AD1F-4555-9827-0DD9335611A4),
		helpstring("Windows Thumbnail Plugin")
	]
	coclass ImageService
	{
		[default] interface IImageServicePlugin;
	};
};
