#ifndef MINIUPNPCSTRINGS_H_INCLUDED
#define MINIUPNPCSTRINGS_H_INCLUDED

#define OS_STRING "PeerProject/1.0.2.0"
#define MINIUPNPC_VERSION_STRING "1.9.20141120"
#define UPNP_VERSION_STRING "UPnP/1.1"

#endif
